version: '3.9'
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cloud-1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  # wordpress:
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   image: wordpress:latest
  #   container_name: wordpress
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     WORDPRESS_DB_HOST: ${DB_HOST}
  #     WORDPRESS_DB_USER: ${MYSQL_USER}
  #     WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
  #     WORDPRESS_DB_NAME: wordpress
  #   ports:
  #     - "9000:80"
  #   volumes:
  #     - wp_data:/var/www/html
  #     - ./entrypoint.sh:/var/www/html/entrypoint.sh:ro
  #   networks:
  #     - cloud-1
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_SITE_URL: http://localhost:9000
      WORDPRESS_TITLE: "My WordPress Site"
      WORDPRESS_ADMIN_USER: user
      WORDPRESS_ADMIN_PASSWORD: pass
      WORDPRESS_ADMIN_EMAIL: admin@example.com
    ports:
      - "9000:80"
    volumes:
      - wp_data:/var/www/html
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    networks:
      - cloud-1

  phpmyadmin:
    depends_on:
      db:
        condition: service_healthy
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8180:80"
    env_file: .env
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${PHPMYADMIN_PASSWORD}
    networks:
      - cloud-1

volumes:
  db_data:
    driver: local
  wp_data:
    driver: local

networks:
  cloud-1:
    driver: bridge
