---
- name: Build Docker image for Go application
  command: docker build -t go-app /home/{{ ansible_user }}

- name: Stop and remove old Go app container (if exists)
  command: docker rm -f go-app-container
  ignore_errors: true

- name: Run Docker container for Go application
  command: >
    docker run -d --name go-app-container -p 8080:8080 go-app
