---
- name: Install Docker dependencies
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: true

- name: Add Docker GPG key
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: true
