---
  - name: Install Docker Engine
    apt:
      name: docker-ce
      state: latest
      update_cache: yes

  - name: Ensure Docker service is started and enabled
    service:
      name: docker
      state: started
      enabled: yes

  - name: Install Docker Compose
    get_url:
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x'