---
  - name: Copy docker-compose.yml to EC2 instance
    copy:
      src: ../srcs/docker-compose.yml
      dest: "{{ project_dir }}/docker-compose.yml"
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Copy docker-compose.yml to EC2 instance
    copy:
      src: ../srcs/docker-compose.yml
      dest: "{{ project_dir }}/docker-compose.yml"
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Copy Dockerfile to EC2 instance
    copy:
      src: ../srcs/Dockerfile
      dest: "{{ project_dir }}/Dockerfile"
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Copy apache config to EC2 instance
    copy:
      src: ../srcs/apache
      dest: "{{ project_dir }}/"
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Copy entrypoint script to EC2 instance
    copy:
      src: ../srcs/entrypoint.sh
      dest: "{{ project_dir }}/entrypoint.sh"
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Copy .env file to EC2 instance
    copy:
      src: ../srcs/.env
      dest: "{{ project_dir }}/.env"
      owner: ubuntu
      group: ubuntu
      mode: '0644'