---
  - name: Copy docker-compose.yml to DO droplets
    copy:
      src: ../srcs/docker-compose.yml
      dest: "{{ project_dir }}/docker-compose.yml"
      owner: root
      group: root
      mode: '0644'

  - name: Copy docker-compose.yml to DO droplets
    copy:
      src: ../srcs/docker-compose.yml
      dest: "{{ project_dir }}/docker-compose.yml"
      owner: root
      group: root
      mode: '0644'

  - name: Copy Dockerfile to DO droplets
    copy:
      src: ../srcs/Dockerfile
      dest: "{{ project_dir }}/Dockerfile"
      owner: root
      group: root
      mode: '0644'

  - name: Copy apache config to DO droplets
    copy:
      src: ../srcs/apache
      dest: "{{ project_dir }}/"
      owner: root
      group: root
      mode: '0644'

  - name: Copy entrypoint script to DO droplets
    copy:
      src: ../srcs/entrypoint.sh
      dest: "{{ project_dir }}/entrypoint.sh"
      owner: root
      group: root
      mode: '0644'

  - name: Copy .env file to DO droplets
    copy:
      src: ../srcs/.env
      dest: "{{ project_dir }}/.env"
      owner: root
      group: root
      mode: '0644'

  - name: Get public IP of the DO droplets
    uri:
      url: http://checkip.amazonaws.com
      return_content: yes
    register: public_ip

  - name: Add WP_URL to .env
    lineinfile:
      path: ../srcs/.env
      line: "WP_URL=https://{{ public_ip.content | trim }}:9443"
      create: yes