- name: Deploy WordPress with Docker Compose
  hosts: ec2
  become: yes
  vars:
    project_dir: /home/ubuntu/wordpress
  tasks:
    - name: Create project directory
      file:
        path: "{{ project_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy docker-compose.yml to EC2 instance
      copy:
        src: ../srcs/docker-compose.yml
        dest: "{{ project_dir }}/docker-compose.yml"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Copy docker-compose.yml to EC2 instance
      copy:
        src: ../srcs/docker-compose.yml
        dest: "{{ project_dir }}/docker-compose.yml"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Copy .env file to EC2 instance
      copy:
        src: ../srcs/.env
        dest: "{{ project_dir }}/.env"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Deploy Docker Compose stack
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        state: present
